title: "Maine Aguilar"
description: "Tech notes, Atlassian, Automation, and Systems Administration"
url: "https://ryushinobi.net"

theme: minimal-mistakes-jekyll

minimal_mistakes_skin: neon

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      toc: false

sass:
  style: compressed
